@startuml

class RangedEnemy  {
    [[vscode://file/E:/School_stuff/Game/labor-projekt/Enemies/RangedEnemy/RangedEnemy.cs ScriptFile]]
    [Properties]
    [[vscode://file/E:/School_stuff/Game/labor-projekt/Enemies/RangedEnemy/RangedEnemy.cs:11 attackAngle]]
    --
    [Methods]
    [[vscode://file/E:/School_stuff/Game/labor-projekt/Enemies/RangedEnemy/RangedEnemy.cs:65 FindTarget()]]
    [[vscode://file/E:/School_stuff/Game/labor-projekt/Enemies/RangedEnemy/RangedEnemy.cs:118 IsTargetVisible()]]
    [[vscode://file/E:/School_stuff/Game/labor-projekt/Enemies/RangedEnemy/RangedEnemy.cs:23 Navigate()]]
    [[vscode://file/E:/School_stuff/Game/labor-projekt/Enemies/RangedEnemy/RangedEnemy.cs:44 TryAttack()]]
}

@enduml